name: Build and Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build bundle with Docker Compose
        run: docker compose -f compose.yaml run --rm h5web-wrapper

      - name: tree
        run: tree

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./app/dist

  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
